-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_rst_r : IN STD_LOGIC;
    write_en : IN STD_LOGIC;
    write_index : IN STD_LOGIC_VECTOR (5 downto 0);
    x_in : IN STD_LOGIC_VECTOR (7 downto 0);
    w_in : IN STD_LOGIC_VECTOR (7 downto 0);
    start_r : IN STD_LOGIC;
    clear_done : IN STD_LOGIC;
    result : OUT STD_LOGIC_VECTOR (31 downto 0);
    done : OUT STD_LOGIC );
end;


architecture behav of conv is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv_conv,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu5p-flva2104-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=2.186500,HLS_SYN_LAT=4,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=530,HLS_SYN_LUT=305,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

    signal comp_index : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal acc : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal state : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal done_r : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal x_mem_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_mem_V_ce0 : STD_LOGIC;
    signal x_mem_V_we0 : STD_LOGIC;
    signal x_mem_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_mem_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal w_mem_V_ce0 : STD_LOGIC;
    signal w_mem_V_we0 : STD_LOGIC;
    signal w_mem_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal clear_done_read_reg_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal clear_done_read_reg_312_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal clear_done_read_reg_312_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal start_r_read_read_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal start_r_read_reg_316 : STD_LOGIC_VECTOR (0 downto 0);
    signal start_r_read_reg_316_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal start_r_read_reg_316_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal start_r_read_reg_316_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_read_read_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_read_reg_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_read_reg_320_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_read_reg_320_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_read_reg_320_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal state_load_load_fu_221_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_load_reg_324 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_load_reg_324_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal state_load_reg_324_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal state_load_reg_324_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln874_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln874_reg_341 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln874_reg_341_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln874_reg_341_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln874_reg_341_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_phi_mux_acc_loc_0_phi_fu_178_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_301_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter4_acc_loc_0_reg_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_acc_loc_0_reg_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_acc_loc_0_reg_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter2_acc_loc_0_reg_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter3_acc_loc_0_reg_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln538_1_fu_237_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal and_ln52_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln538_fu_249_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln695_1_fu_261_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_acc_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln882_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln52_fu_231_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_156 : BOOLEAN;
    signal ap_condition_286 : BOOLEAN;

    component conv_mac_muladd_8s_8s_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_x_mem_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    x_mem_V_U : component conv_x_mem_V
    generic map (
        DataWidth => 8,
        AddressRange => 40,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => x_mem_V_address0,
        ce0 => x_mem_V_ce0,
        we0 => x_mem_V_we0,
        d0 => x_in,
        q0 => x_mem_V_q0);

    w_mem_V_U : component conv_x_mem_V
    generic map (
        DataWidth => 8,
        AddressRange => 40,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_mem_V_address0,
        ce0 => w_mem_V_ce0,
        we0 => w_mem_V_we0,
        d0 => w_in,
        q0 => w_mem_V_q0);

    mac_muladd_8s_8s_32ns_32_4_1_U1 : component conv_mac_muladd_8s_8s_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => w_mem_V_q0,
        din1 => x_mem_V_q0,
        din2 => ap_sig_allocacmp_acc_load,
        ce => ap_const_logic_1,
        dout => grp_fu_301_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    acc_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_load_reg_324_pp0_iter3_reg = ap_const_lv1_1) and (ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                acc <= grp_fu_301_p3;
            elsif ((((state_load_reg_324_pp0_iter3_reg = ap_const_lv1_0) and (ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_1) and (start_r_read_reg_316_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
                acc <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_acc_loc_0_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_rst_read_read_fu_110_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (start_r_read_read_fu_80_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
                ap_phi_reg_pp0_iter1_acc_loc_0_reg_174 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter1_acc_loc_0_reg_174 <= ap_phi_reg_pp0_iter0_acc_loc_0_reg_174;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_acc_loc_0_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_156)) then 
                    ap_phi_reg_pp0_iter4_acc_loc_0_reg_174 <= ap_sig_allocacmp_acc_load;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_acc_loc_0_reg_174 <= ap_phi_reg_pp0_iter3_acc_loc_0_reg_174;
                end if;
            end if; 
        end if;
    end process;

    comp_index_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln874_fu_255_p2 = ap_const_lv1_0) and (state_load_load_fu_221_p1 = ap_const_lv1_1) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
                comp_index <= add_ln695_1_fu_261_p2;
            elsif ((((ap_rst_read_read_fu_110_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (start_r_read_read_fu_80_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
                comp_index <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    done_r_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln874_reg_341_pp0_iter2_reg = ap_const_lv1_1) and (state_load_reg_324_pp0_iter2_reg = ap_const_lv1_1) and (ap_rst_read_reg_320_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                done_r <= ap_const_lv1_1;
            elsif ((((ap_rst_read_reg_320_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((state_load_reg_324_pp0_iter2_reg = ap_const_lv1_0) and (ap_rst_read_reg_320_pp0_iter2_reg = ap_const_lv1_1) and (clear_done_read_reg_312_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
                done_r <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (start_r_read_read_fu_80_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
                state <= ap_const_lv1_1;
            elsif ((((icmp_ln874_fu_255_p2 = ap_const_lv1_1) and (state_load_load_fu_221_p1 = ap_const_lv1_1) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((ap_rst_read_read_fu_110_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
                state <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter2_acc_loc_0_reg_174 <= ap_phi_reg_pp0_iter1_acc_loc_0_reg_174;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_acc_loc_0_reg_174 <= ap_phi_reg_pp0_iter2_acc_loc_0_reg_174;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_rst_read_reg_320 <= (0=>ap_rst_r, others=>'-');
                ap_rst_read_reg_320_pp0_iter1_reg <= ap_rst_read_reg_320;
                clear_done_read_reg_312 <= (0=>clear_done, others=>'-');
                clear_done_read_reg_312_pp0_iter1_reg <= clear_done_read_reg_312;
                icmp_ln874_reg_341_pp0_iter1_reg <= icmp_ln874_reg_341;
                start_r_read_reg_316 <= (0=>start_r, others=>'-');
                start_r_read_reg_316_pp0_iter1_reg <= start_r_read_reg_316;
                state_load_reg_324 <= state;
                state_load_reg_324_pp0_iter1_reg <= state_load_reg_324;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_rst_read_reg_320_pp0_iter2_reg <= ap_rst_read_reg_320_pp0_iter1_reg;
                ap_rst_read_reg_320_pp0_iter3_reg <= ap_rst_read_reg_320_pp0_iter2_reg;
                clear_done_read_reg_312_pp0_iter2_reg <= clear_done_read_reg_312_pp0_iter1_reg;
                icmp_ln874_reg_341_pp0_iter2_reg <= icmp_ln874_reg_341_pp0_iter1_reg;
                icmp_ln874_reg_341_pp0_iter3_reg <= icmp_ln874_reg_341_pp0_iter2_reg;
                start_r_read_reg_316_pp0_iter2_reg <= start_r_read_reg_316_pp0_iter1_reg;
                start_r_read_reg_316_pp0_iter3_reg <= start_r_read_reg_316_pp0_iter2_reg;
                state_load_reg_324_pp0_iter2_reg <= state_load_reg_324_pp0_iter1_reg;
                state_load_reg_324_pp0_iter3_reg <= state_load_reg_324_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((state_load_load_fu_221_p1 = ap_const_lv1_1) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln874_reg_341 <= icmp_ln874_fu_255_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln695_1_fu_261_p2 <= std_logic_vector(unsigned(comp_index) + unsigned(ap_const_lv6_1));
    and_ln52_fu_231_p1 <= (0=>write_en, others=>'-');
    and_ln52_fu_231_p2 <= (icmp_ln882_fu_225_p2 and and_ln52_fu_231_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_156_assign_proc : process(start_r_read_reg_316_pp0_iter2_reg, ap_rst_read_reg_320_pp0_iter2_reg, state_load_reg_324_pp0_iter2_reg)
    begin
                ap_condition_156 <= ((state_load_reg_324_pp0_iter2_reg = ap_const_lv1_0) and (ap_rst_read_reg_320_pp0_iter2_reg = ap_const_lv1_1) and (start_r_read_reg_316_pp0_iter2_reg = ap_const_lv1_0));
    end process;


    ap_condition_286_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_rst_read_read_fu_110_p2, ap_block_pp0_stage0)
    begin
                ap_condition_286 <= ((ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_acc_loc_0_phi_fu_178_p10_assign_proc : process(ap_rst_read_reg_320_pp0_iter3_reg, state_load_reg_324_pp0_iter3_reg, icmp_ln874_reg_341_pp0_iter3_reg, grp_fu_301_p3, ap_phi_reg_pp0_iter4_acc_loc_0_reg_174)
    begin
        if ((((icmp_ln874_reg_341_pp0_iter3_reg = ap_const_lv1_0) and (state_load_reg_324_pp0_iter3_reg = ap_const_lv1_1) and (ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_1)) or ((icmp_ln874_reg_341_pp0_iter3_reg = ap_const_lv1_1) and (state_load_reg_324_pp0_iter3_reg = ap_const_lv1_1) and (ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_1)))) then 
            ap_phi_mux_acc_loc_0_phi_fu_178_p10 <= grp_fu_301_p3;
        else 
            ap_phi_mux_acc_loc_0_phi_fu_178_p10 <= ap_phi_reg_pp0_iter4_acc_loc_0_reg_174;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_acc_loc_0_reg_174 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_reset_idle_pp0 <= ap_const_logic_0;
    ap_rst_read_read_fu_110_p2 <= (0=>ap_rst_r, others=>'-');

    ap_sig_allocacmp_acc_load_assign_proc : process(acc, start_r_read_reg_316_pp0_iter3_reg, ap_rst_read_reg_320_pp0_iter3_reg, state_load_reg_324_pp0_iter3_reg, ap_enable_reg_pp0_iter4, grp_fu_301_p3, ap_block_pp0_stage0)
    begin
        if (((state_load_reg_324_pp0_iter3_reg = ap_const_lv1_1) and (ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            ap_sig_allocacmp_acc_load <= grp_fu_301_p3;
        elsif ((((state_load_reg_324_pp0_iter3_reg = ap_const_lv1_0) and (ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_1) and (start_r_read_reg_316_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_rst_read_reg_320_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)))) then 
            ap_sig_allocacmp_acc_load <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_acc_load <= acc;
        end if; 
    end process;

    done <= done_r(0);
    icmp_ln874_fu_255_p2 <= "1" when (comp_index = ap_const_lv6_27) else "0";
    icmp_ln882_fu_225_p2 <= "1" when (unsigned(write_index) < unsigned(ap_const_lv6_28)) else "0";
    result <= ap_phi_mux_acc_loc_0_phi_fu_178_p10;
    start_r_read_read_fu_80_p2 <= (0=>start_r, others=>'-');
    state_load_load_fu_221_p1 <= state;

    w_mem_V_address0_assign_proc : process(state_load_load_fu_221_p1, zext_ln538_1_fu_237_p1, and_ln52_fu_231_p2, zext_ln538_fu_249_p1, ap_condition_286)
    begin
        if ((ap_const_boolean_1 = ap_condition_286)) then
            if ((state_load_load_fu_221_p1 = ap_const_lv1_1)) then 
                w_mem_V_address0 <= zext_ln538_fu_249_p1(6 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln52_fu_231_p2) and (state_load_load_fu_221_p1 = ap_const_lv1_0))) then 
                w_mem_V_address0 <= zext_ln538_1_fu_237_p1(6 - 1 downto 0);
            else 
                w_mem_V_address0 <= "XXXXXX";
            end if;
        else 
            w_mem_V_address0 <= "XXXXXX";
        end if; 
    end process;


    w_mem_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_rst_read_read_fu_110_p2, state_load_load_fu_221_p1, and_ln52_fu_231_p2)
    begin
        if ((((state_load_load_fu_221_p1 = ap_const_lv1_1) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((ap_const_lv1_1 = and_ln52_fu_231_p2) and (state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
            w_mem_V_ce0 <= ap_const_logic_1;
        else 
            w_mem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    w_mem_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_rst_read_read_fu_110_p2, state_load_load_fu_221_p1, and_ln52_fu_231_p2)
    begin
        if (((ap_const_lv1_1 = and_ln52_fu_231_p2) and (state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
            w_mem_V_we0 <= ap_const_logic_1;
        else 
            w_mem_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_mem_V_address0_assign_proc : process(state_load_load_fu_221_p1, zext_ln538_1_fu_237_p1, and_ln52_fu_231_p2, zext_ln538_fu_249_p1, ap_condition_286)
    begin
        if ((ap_const_boolean_1 = ap_condition_286)) then
            if ((state_load_load_fu_221_p1 = ap_const_lv1_1)) then 
                x_mem_V_address0 <= zext_ln538_fu_249_p1(6 - 1 downto 0);
            elsif (((ap_const_lv1_1 = and_ln52_fu_231_p2) and (state_load_load_fu_221_p1 = ap_const_lv1_0))) then 
                x_mem_V_address0 <= zext_ln538_1_fu_237_p1(6 - 1 downto 0);
            else 
                x_mem_V_address0 <= "XXXXXX";
            end if;
        else 
            x_mem_V_address0 <= "XXXXXX";
        end if; 
    end process;


    x_mem_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_rst_read_read_fu_110_p2, state_load_load_fu_221_p1, and_ln52_fu_231_p2)
    begin
        if ((((state_load_load_fu_221_p1 = ap_const_lv1_1) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)) or ((ap_const_lv1_1 = and_ln52_fu_231_p2) and (state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1)))) then 
            x_mem_V_ce0 <= ap_const_logic_1;
        else 
            x_mem_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_mem_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_rst_read_read_fu_110_p2, state_load_load_fu_221_p1, and_ln52_fu_231_p2)
    begin
        if (((ap_const_lv1_1 = and_ln52_fu_231_p2) and (state_load_load_fu_221_p1 = ap_const_lv1_0) and (ap_rst_read_read_fu_110_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then 
            x_mem_V_we0 <= ap_const_logic_1;
        else 
            x_mem_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln538_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(write_index),64));
    zext_ln538_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(comp_index),64));
end behav;
